name: Deploy to EC2

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    # If using Environment secrets, uncomment the line below and replace 'production' with your environment name:
    # environment: production
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          # If using Variables instead of Secrets, change 'secrets.' to 'vars.'
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/CTF-Recon-Web
            git pull origin main
            source venv/bin/activate
            pip install -r requirements.txt
            sudo systemctl restart ctfrecon
